"""OIDC Authentication service"""

import logging
import secrets
import hashlib
import base64
import json
import httpx
from datetime import datetime

from ..storage.sqlite import SQLiteStorage
from ..services.auth import AuthService
from ..oidc_models import OIDCProvider, OIDCUserInfo
from ..models import User, Session, TokenPair

logger = logging.getLogger(__name__)


def generate_pkce_pair() -> tuple[str, str]:
    """Generate PKCE code_verifier and code_challenge"""
    # code_verifier: 43-128 character random URL-safe string
    code_verifier = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode().rstrip("=")
    # code_challenge: SHA256(code_verifier) then Base64URL encode
    code_challenge = (
        base64.urlsafe_b64encode(hashlib.sha256(code_verifier.encode()).digest())
        .decode()
        .rstrip("=")
    )
    return code_verifier, code_challenge


def _require_user_id(user: User) -> int:
    if user.id is None:
        raise ValueError("OIDC user must have a persisted id")
    return user.id


class OIDCService:
    """OIDC Authentication service"""

    def __init__(self, storage: SQLiteStorage, auth_service: AuthService):
        self.storage = storage
        self.auth_service = auth_service

    async def _get_provider_endpoints(self, provider: OIDCProvider) -> OIDCProvider:
        """Automatically fill endpoint URLs through OIDC Discovery"""
        if provider.discovery_enabled and provider.issuer_url:
            discovery_url = f"{provider.issuer_url.rstrip('/')}/.well-known/openid-configuration"
            try:
                async with httpx.AsyncClient(timeout=10) as client:
                    resp = await client.get(discovery_url)
                    resp.raise_for_status()
                    config = resp.json()
                provider.authorization_url = config["authorization_endpoint"]
                provider.token_url = config["token_endpoint"]
                provider.userinfo_url = config.get("userinfo_endpoint") or provider.userinfo_url
                provider.jwks_uri = config.get("jwks_uri") or provider.jwks_uri
                logger.info(f"OIDC Discovery 成功：{provider.name}")
            except Exception as e:
                logger.warning(f"OIDC Discovery 失败（{provider.name}）：{e}")
                if not (provider.authorization_url and provider.token_url):
                    raise ValueError("OIDC Discovery 失败且未配置手动端点")
        return provider

    async def get_authorization_url(
        self, provider_slug: str, redirect_uri: str, state: str, code_challenge: str
    ) -> str:
        """Generate an OAuth2 authorization URL and store state/PKCE"""
        provider = await self.storage.get_oauth_provider(provider_slug)
        if not provider or not provider.enabled:
            raise ValueError(f"提供商 {provider_slug} 不存在或已禁用")

        provider = await self._get_provider_endpoints(provider)

        # Get the PKCE verifier from the caller-provided code_verifier
        # The provided code_challenge was generated by the router layer and stored in the database
        auth_url = (
            f"{provider.authorization_url}"
            f"?response_type=code"
            f"&client_id={provider.client_id}"
            f"&redirect_uri={redirect_uri}"
            f"&scope={provider.scopes}"
            f"&state={state}"
            f"&code_challenge={code_challenge}"
            f"&code_challenge_method=S256"
        )
        return auth_url

    async def handle_callback(
        self,
        provider_slug: str,
        code: str,
        redirect_uri: str,
        code_verifier: str,
        user_agent: str | None = None,
        ip_address: str | None = None,
    ) -> tuple[User, TokenPair]:
        """Handle OIDC callback: exchange token, fetch user info, create or link user"""
        provider = await self.storage.get_oauth_provider(provider_slug)
        if not provider:
            raise ValueError(f"提供商 {provider_slug} 不存在")

        provider = await self._get_provider_endpoints(provider)

        # 1. Exchange code for access_token
        # Most standard OIDC IdPs, such as Authentik and Keycloak, require Basic Auth (client_secret_basic) by default
        token_data = {
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": redirect_uri,
            "client_id": provider.client_id,
            "code_verifier": code_verifier,
        }
        async with httpx.AsyncClient(timeout=15) as http:
            try:
                if provider.client_secret:
                    token_resp = await http.post(
                        str(provider.token_url),
                        data=token_data,
                        headers={"Content-Type": "application/x-www-form-urlencoded"},
                        auth=(provider.client_id, provider.client_secret),
                    )
                else:
                    token_resp = await http.post(
                        str(provider.token_url),
                        data=token_data,
                        headers={"Content-Type": "application/x-www-form-urlencoded"},
                    )
                token_resp.raise_for_status()
                token = token_resp.json()
            except httpx.HTTPStatusError as e:
                logger.error(f"Token 换取失败：{e.response.status_code} {e.response.text}")
                raise ValueError(f"Token 换取失败：{e.response.status_code}")

        # 2. Fetch user information
        if token.get("id_token"):
            userinfo = self._parse_id_token(token["id_token"], provider_slug)
        else:
            async with httpx.AsyncClient(timeout=10) as http:
                ui_resp = await http.get(
                    str(provider.userinfo_url),
                    headers={"Authorization": f"Bearer {token['access_token']}"},
                )
                ui_resp.raise_for_status()
                userinfo = self._normalize_userinfo(ui_resp.json(), provider_slug)

        # 3. Create or link user
        user = await self._get_or_create_user(userinfo)

        # 4. Generate JWT
        token_pair = self.auth_service._create_token_pair(user)

        # 5. Create a session
        import jwt as pyjwt

        user_id = _require_user_id(user)

        session = Session(
            user_id=user_id,
            token_hash=self.auth_service._hash_token(token_pair.access_token),
            refresh_token_hash=self.auth_service._hash_token(token_pair.refresh_token),
            user_agent=user_agent,
            ip_address=ip_address,
            expires_at=datetime.fromtimestamp(
                pyjwt.decode(
                    token_pair.access_token,
                    key=self.auth_service.secret_key,
                    algorithms=["HS256"],
                )["exp"]
            ),
        )
        await self.storage.create_session(session)

        return user, token_pair

    def _parse_id_token(self, id_token: str, provider_slug: str) -> OIDCUserInfo:
        """Parse JWT ID Token without signature verification, only to read claims"""
        parts = id_token.split(".")
        if len(parts) != 3:
            raise ValueError("ID Token 格式无效")
        payload = parts[1]
        # Add Base64 padding
        payload += "=" * (4 - len(payload) % 4)
        claims = json.loads(base64.urlsafe_b64decode(payload))
        return OIDCUserInfo(
            sub=claims["sub"],
            email=claims.get("email", f"{claims['sub']}@{provider_slug}.local"),
            email_verified=claims.get("email_verified", False),
            name=claims.get("name"),
            preferred_username=claims.get("preferred_username"),
            picture=claims.get("picture"),
            provider_slug=provider_slug,
        )

    def _normalize_userinfo(self, data: dict, provider_slug: str) -> OIDCUserInfo:
        """Normalize data returned by the userinfo endpoint"""
        return OIDCUserInfo(
            sub=data["sub"],
            email=data.get("email", f"{data['sub']}@{provider_slug}.local"),
            email_verified=data.get("email_verified", False),
            name=data.get("name"),
            preferred_username=data.get("preferred_username"),
            picture=data.get("picture"),
            provider_slug=provider_slug,
        )

    async def _get_or_create_user(self, userinfo: OIDCUserInfo) -> User:
        """Get or create an OIDC user with three-step matching"""
        # 1. Match by OIDC sub
        existing = await self.storage.get_user_by_oauth(userinfo.provider_slug, userinfo.sub)
        if existing:
            # Synchronize avatar and email
            if userinfo.email_verified or userinfo.picture:
                await self.storage.update_user_oidc_info(
                    _require_user_id(existing),
                    email=userinfo.email if userinfo.email_verified else None,
                    avatar_url=userinfo.picture,
                )
            return existing

        # 2. Match by username and link automatically
        username = userinfo.preferred_username or userinfo.email.split("@")[0]
        by_username = await self.storage.get_user_by_username(username)
        if by_username:
            await self.storage.link_oauth_to_user(
                _require_user_id(by_username),
                userinfo.provider_slug,
                userinfo.sub,
                userinfo.picture,
            )
            return by_username

        # 3. Create a new user
        user = User(
            username=username,
            email=userinfo.email,
            password_hash=None,  # OIDC users have no password
            oauth_provider=userinfo.provider_slug,
            oauth_sub=userinfo.sub,
            avatar_url=userinfo.picture,
            status="active",
        )
        return await self.storage.create_user(user)
